### ISSUE TITLE
Support WebAssembly

### ISSUE THREAD

**Issue by dullbananas** [fasterthanlime/rc-zip#16]
Error when compiling to `wasm32-unknown-unknown`:

```
   Compiling rc-zip v0.0.1
error[E0277]: the trait bound `std::fs::File: ReadAt` is not satisfied
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rc-zip-0.0.1/src/reader/read_zip.rs:64:36
   |
64 |         ReadAt::read_zip_with_size(self, size)
   |                                    ^^^^ the trait `ReadAt` is not implemented for `std::fs::File`
   |
   = note: required for the cast to the object type `dyn ReadAt`
```

**Comment by kotx** [comment]
Maybe we can lock all `std::fs::File` usage in this crate behind a (default) feature for now? Might help with WASM compatibility

**Comment by fasterthanlime** [comment]
> Maybe we can lock all `std::fs::File` usage in this crate behind a (default) feature for now? Might help with WASM compatibility

That'd be fine. I'm not actively maintaining `rc-zip` right now, so I might need to add maintainers at some point.

**Comment by fasterthanlime** [comment]
> Maybe we can lock all `std::fs::File` usage in this crate behind a (default) feature for now? Might help with WASM compatibility

As of ae235921328b62e79760f870849f55bec5805c4d that's the case, but then the crate isn't very useful - the `sync` package contains a lot of logic still.

The next issue is that the `positioned-io` crate doesn't build on wasm32-unknown-unknown:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/7998310/229142930-10441e79-5711-4349-9f63-c761ba11458a.png">

Ideally rc-zip would provide its own trait there so it could at least be usable on `&[u8]` or something from wasm.

**Comment by boredcoder411** [comment]
so... is this wasm-ready?
