### ISSUE TITLE
Does this library support file contents?

### ISSUE THREAD

**Issue by muja** [fasterthanlime/rc-zip#24]
I see it mentioned nowhere and i don't see any tests/examples/docs about payload?
I was looking for a good 10 minutes...

Maybe it could be documented if not

**Comment by fasterthanlime** [comment]
Yes. Here's where the unit tests check the entries' contents:

https://github.com/fasterthanlime/rc-zip/blob/2197bdd7900246fb044a2961c2f37f347b300ef4/crates/rc-zip/src/tests.rs#L117-L137

**Comment by muja** [comment]
Okay it does, there is `entry.reader()` for SyncZipEntry.

**Comment by muja** [comment]
Yeah but for the general `Archive` it seems to not have one? So if one uses the ArchiveReader directly, there seems to be no way to get to the payload?

**Comment by fasterthanlime** [comment]
> Yeah but for the general `Archive` it seems to not have one? So if one uses the ArchiveReader directly, there seems to be no way to get to the payload?

rc-zip follows the "sans-io" approach so you can bring your own I/O (sync, async, etc.)

It also ships with a sync I/O implementation, you can look at the `jean` sample to get a sense of how to use it:

https://github.com/fasterthanlime/rc-zip/blob/2197bdd7900246fb044a2961c2f37f347b300ef4/crates/jean/src/main.rs#L267

As I'm going over the rustdocs, they seem misleading - they do point you to `ArchiveReader`, but really what you probably want is to just use the `ReadZip` trait: https://docs.rs/rc-zip/latest/rc_zip/reader/sync/trait.ReadZip.html
