### ISSUE TITLE
error management: avoid exposing types from dependencies from rc_zip::Error

### ISSUE THREAD

**Issue by Geal** [fasterthanlime/rc-zip#4]
instead of forcing errors to fit into `io::Error`, it would be easier to have a dedicated error enum that can hold a `io::Error`. As an example, see https://github.com/wyyerd/pulsar-rs/blob/master/client/src/error.rs
It can be written manually, or through a proc macro with the failure crate

**Comment by fasterthanlime** [comment]
Do you mean this?

https://github.com/rust-compress/rc-zip/blob/69b884f85085c5c99a846703f83ddc48e0d086ac/src/error.rs#L4-L18

I sort of liked the read() methods only returning `std::io::Error` (to actually separate I/O and parsing) but I suppose it doesn't make sense for EntryReader.

**Comment by Geal** [comment]
you can go further and make sure the error API does not expose types from dependencies, because if they change, it will break your API. In that case you convert the dependency's error type to your own (which unfortunately involves a lot of boilerplate). But for `std::io::Error`, it's pretty standard :)

**Comment by fasterthanlime** [comment]
Ok, so it looks like we're 90% there, we just need to make sure `encoding::DecodingError` doesn't expose types from dependencies.

**Comment by fasterthanlime** [comment]
> instead of forcing errors to fit into `io::Error`, it would be easier to have a dedicated error enum that can hold a `io::Error`

Thinking more about this: that doesn't seem possible if we want `EntryReader` to implement `std::io::Read` !

**Comment by fasterthanlime** [comment]
I've decided to not care about this until someone who's actively using the crate complains about it.
